services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CodeFareith\CfGoogleAuthenticator\:
    resource: '../Classes/*'

  CodeFareith\CfGoogleAuthenticator\Handler\GoogleAuthenticatorSetupHandler:
    public: true
