services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CodeFareith\CfGoogleAuthenticator\:
    resource: '../Classes/*'
    exclude: [
      '../Classes/Validation/Validator/TYPO3v11/*'
    ]

  CodeFareith\CfGoogleAuthenticator\Handler\GoogleAuthenticatorSetupHandler:
    public: true
